/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proy_2_arb_gen;

/**
 * Ventana encargada de mostrar los datos completos de cualquier Lord que 
 * sea seleccionado en el arbol.
 */

public class VentanaDetalleLord extends javax.swing.JFrame {

    /**
     * Valor de caracteres maximos por linea
     */
    
    private final int MAX_CHARACTERS_PER_LINE = 60;

    /**
     * Constructor de VentanaDetalleLord cuando se le pasa la ventana principal y el lord a usar
     * 
     * @param ventanaPrincipal la ventana principal de la interfaz
     * @param lord el lord al cual se le van a mostrar los datos
     */

    public VentanaDetalleLord(VentanaPrincipal ventanaPrincipal, Lord lord) {
        this.setLocationRelativeTo(ventanaPrincipal);
        initComponents();
        
        String detalles = lord.completeDataToString().replace("\t\t", "|").replace("\t", "").replace("|", "\t");
        String[] lines = detalles.split("\n");
        this.jLabelLordFullName.setText(lord.fullName);
        this.jTextAreaDetalles.setText("");
        for (int i = 1; i < lines.length; i++) {
            if (lines[i].length() > MAX_CHARACTERS_PER_LINE) {
                String[] innerStrings = lines[i].split(" ");
                int tamLinea = 0;
                for (int j = 0; j < innerStrings.length; j++) {
                    tamLinea += innerStrings[j].length() + 1;
                    if (tamLinea > MAX_CHARACTERS_PER_LINE) {
                        this.jTextAreaDetalles.append(innerStrings[j] + "\n\t");
                        tamLinea = 0;
                    } else {
                        if (j == innerStrings.length - 1) {
                            this.jTextAreaDetalles.append(innerStrings[j] + "\n");
                        } else {
                            this.jTextAreaDetalles.append(innerStrings[j] + " ");
                        }
                    }
                }
            } else {
                this.jTextAreaDetalles.append(lines[i] + "\n");
            }

        }
    }

    /**
     * Constructor de VentanaDetalleLord 
     */

    public VentanaDetalleLord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLordFullName = new javax.swing.JLabel();
        jScrollPaneDetalles = new javax.swing.JScrollPane();
        jTextAreaDetalles = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelLordFullName.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabelLordFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLordFullName.setText("Lord Full Name");
        jLabelLordFullName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextAreaDetalles.setEditable(false);
        jTextAreaDetalles.setColumns(20);
        jTextAreaDetalles.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jTextAreaDetalles.setRows(5);
        jScrollPaneDetalles.setViewportView(jTextAreaDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLordFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLordFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDetalleLord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLordFullName;
    private javax.swing.JScrollPane jScrollPaneDetalles;
    private javax.swing.JTextArea jTextAreaDetalles;
    // End of variables declaration//GEN-END:variables
}
