/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proy_2_arb_gen;


public class VentanaDetalleLord extends javax.swing.JFrame {
    
    private final int MAX_CHARACTERS_PER_LINE = 60;
   
   public VentanaDetalleLord(VentanaPrincipal ventanaPrincipal, Lord lord) {
       this.setLocationRelativeTo(ventanaPrincipal);
        initComponents();
        this.jLabelLordFullName.setText(lord.fullName);
        String detalles = lord.completeDataToString().replace("\t\t", "|").replace("\t", "").replace("|", "\t");
        String[] lines = detalles.split("\n");
        this.jTextAreaDetalles.setText("");
        for (int i = 1; i < lines.length; i++){
            if (lines[i].length() > MAX_CHARACTERS_PER_LINE){
                String[] innerStrings = lines[i].split(" ");
                int tamLinea = 0;
                for (int j = 0; j < innerStrings.length; j++ ){
                    tamLinea += innerStrings[j].length() + 1;
                    if (tamLinea > MAX_CHARACTERS_PER_LINE){
                        this.jTextAreaDetalles.append(innerStrings[j] + "\n\t");
                        tamLinea = 0;
                    } else {
                        if (j == innerStrings.length - 1){
                            this.jTextAreaDetalles.append(innerStrings[j] + "\n");
                        } else {
                            this.jTextAreaDetalles.append(innerStrings[j] + " ");              
                        }
                    }
                }
            } else {
                this.jTextAreaDetalles.append(lines[i] + "\n");
            }
        }
        
        
    }
   
   
    public VentanaDetalleLord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLordFullName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalles = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelLordFullName.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabelLordFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLordFullName.setText("LORD FULL NAME");
        jLabelLordFullName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextAreaDetalles.setEditable(false);
        jTextAreaDetalles.setColumns(20);
        jTextAreaDetalles.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jTextAreaDetalles.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jLabelLordFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLordFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDetalleLord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDetalleLord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLordFullName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetalles;
    // End of variables declaration//GEN-END:variables
}
